### ISSUE TITLE
Popper position calculation fails if wrapper is position relative

### ISSUE THREAD

**Issue by claudiobmgrtnr** [FezVrasta/popper.js#174]
### CodePen demo

Reference to the #wrapper
http://codepen.io/claudiobmgrtnr/pen/RpbQqq

<img width="180" alt="popper-lost-in-space" src="https://cloud.githubusercontent.com/assets/3873078/23224474/e223ad3c-f92e-11e6-9d52-51694014b843.png">

Update:
Reference to the #ref
http://codepen.io/claudiobmgrtnr/pen/evYOzN

<img width="149" alt="popper-lost" src="https://cloud.githubusercontent.com/assets/3873078/23250493/b1b03d3e-f9a9-11e6-8dd3-68822a163e40.png">

### Steps to reproduce the problem

1.  Create a `wrapper` with `position:relative`
2.  Add a `ref` and `pop` with `position:relative`
3.  Pop the popper: `new Popper(ref, pop)`

### What is the expected behavior?

Popper keeps tooltip element into the viewport

### What went wrong?

Tooltip is outside the viewport

### Any other comments?

We used `80vw` in the codepen but it will also work with `px`

**Comment by FezVrasta** [comment]
you are defining as reference the wrapper... is it intended?

**Comment by claudiobmgrtnr** [comment]
This was not intended but the same issue occurs if you use the ref element:

http://codepen.io/claudiobmgrtnr/pen/evYOzN

**Comment by FezVrasta** [comment]
If you remove the popper element you can see that your reference element already overflows the viewport:
https://codepen.io/FezVrasta/pen/RpwWEw

By default, `preventOverflow` modifier will try to keep the element within its scrollParent element.
https://github.com/FezVrasta/popper.js/blob/master/src/popper/modifiers/index.js#L53

If you change its `boundariesElement` to `viewport` your problem is fixed.
https://codepen.io/FezVrasta/pen/OpJydX

**Comment by claudiobmgrtnr** [comment]
Thank you so much for your time and coming up with a solution.

After looking deeper into it we found out that we didn't manage to reproduce the real underlying problem in this codepens.

Therefore we opened a new bug #177
