### ISSUE TITLE
Breaking changes in minor releases

### ISSUE THREAD

**Issue by lukebatchelor** [FezVrasta/popper.js#218]
Please. Please. PLEASE, don't make breaking changes in minor releases.

You called out that you weren't following semver in the release notes and did it any way.

When you don't follow semver down stream people get affected. Your change completely broke our release pipelines while we tracked down what changed over the weekend and we've now had to pin our versions back whilst we find a work around.

Semver exists for a reason, please follow it properly in the future. :(

**Comment by seancurtis** [comment]
Semver is very powerful. If you're using version numbers, you're using semver. It takes a little getting used to, but becomes second nature after a while.

**Comment by FezVrasta** [comment]
You should use a lockfile or shrinkwrap for extra safety. I'm sorry it caused problems to you but it was a needed change that had to be made and I didn't want to bump a major version because almost nobody used the feature I removed. 

Sorry again for the problems caused by it, I'll be more careful in future.

**Comment by jazoom** [comment]
FYI: a lockfile doesn't protect against this unless you specify the exact version for each module, which is ridiculous. That would make it too tedious to ensure important security patches (for example) make it into the project quickly. NPM's and Yarn's default behaviour is the default for a reason.

**Comment by FezVrasta** [comment]
Default yarn lockfile will actually lock your dependencies to the exact version specified in the lockfile

**Comment by jazoom** [comment]
I know that. I am using Yarn with lockfiles and I have just realised I've been bitten by a breaking change in this library. I didn't realise there was a problem until now because the tooltips just stopped working. I don't even know where the breaking change is yet. I'm not sure if it's this one. For some reason I'm now seeing this error: `Popper is not a constructor`.

You should be able to update libraries according to semver and have them not break.

**Comment by jazoom** [comment]
Update: I just found and fixed the cause of the `Popper is not a constructor` issue. It wasn't this issue. It seems that popper.js is now smarter about whether it is being loaded on client or server and apparently it MUST be loaded on both now. I had been preventing it from crashing the app by only loading it on the client.

**Comment by FezVrasta** [comment]
I can assure you that your error isn't related to a breaking change

**Comment by jazoom** [comment]
Well, there was a change, and it broke the app. That sounds like a breaking change to me. What would you call it?

**Comment by FezVrasta** [comment]
I'd like to know more about the problem you encountered. May you provide more info?

**Comment by jazoom** [comment]
You probably shouldn't worry too much about it since it seems to work fine now just importing the module on the server and client as normal.

popper.js used to crash when loaded on the server so I changed the import to this:

```
// only load popper.js on the client since it references the 'window' object
 
let Popper;
 
if (process.env.VUE_ENV === 'client') {
 
  Popper = require('popper.js');
 
}
 ```

Then after you fixed the behaviour on the server not to rely on window (which is great, thank you) popper.js started giving this error: `Popper is not a constructor`.

Once I figured out what was going it it was easy enough to go back to the normal `import` statement.

**Comment by jazoom** [comment]
To be clear: I'm not blaming you for that change. That's probably not something anyone would have predicted.

**Comment by FezVrasta** [comment]
I see, it's kinda an edge case. I'm sorry for the inconvenience

**Comment by jazoom** [comment]
Yeah it's an edge case. No probs. Thanks for the great library.

**Comment by kevindqc** [comment]
For me, I had to change `import * as Popper from 'popper.js'` to `import Popper from 'popper.js'` (in a TypescriptFile) otherwise I was getting the `Popper is not a constructor` error after upgrading to the latest version. IIRC before my change the Popper was actually an object with a `defaults` property, so that's why it failed to do `new Popper(...)`.

**Comment by FezVrasta** [comment]
It always been a constructor AFAIK
