### ISSUE TITLE
popper.js basic module still not totally browser compatible?

### ISSUE THREAD

**Issue by 719media** [FezVrasta/popper.js#223]
I hate to bring this up because it seems like a lot of crap you had to deal with in this issue:

https://github.com/FezVrasta/popper.js/issues/219

but it looks like the root problem still exists. For example, taking a codepen you wrote awhile back and forking it to the latest version:

https://codepen.io/anon/pen/EmKbRw

You can see that Popper is not defined still occurs, because in the default "module" build you are using dist/esm/popper.js, which is not browser compatible. You can view the file directly:

https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.8.2/popper.js

and see that it's using es6 "export default Popper" at the bottom of the file, meaning the compiled version of code is still not being transpiled correctly.

**Comment by FezVrasta** [comment]
The module target is meant to be used only with bundlers like webpack or browsers that natively support ESM

**Comment by FezVrasta** [comment]
To clarify, you have to use:

```
https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.8.2/umd/popper.js
```

**Comment by JasonTheProgrammer** [comment]
I struggled for a while to find how to include a browser-compatible version of Popper in my project until I stumbled upon this issue and link to CloudFlare.

I'd been trying to user Bower, since my project already uses it for other dependencies, but there's no 'dist' folder like I typically find in Bower packages. And the files in the `src` folder are all depending on some module system. (I'm not very familiar with them, so it's not immediately obvious to me which one). So the install advice `bower install popper.js --save` doesn't really work for me.

Is this an oversight in the Bower package? A limitation of it? Should I be using a different package manager?

**Comment by FezVrasta** [comment]
Hi, yes seems like the Bower package got broken some time ago for some reason.

I fixed the README, by the way, you should really move away from Bower.

![image](https://cloud.githubusercontent.com/assets/5382443/25660813/3cbf9272-300e-11e7-9fa3-be2f4a2ad6f7.png)

**Comment by JasonTheProgrammer** [comment]
Thanks Fez, the updated Bower install documentation using unpkg works well.

Ugh, Bower "no longer recommended"? This is at least the 3rd project in the past year that I've been relying on that's done that. How long until Yarn or NPM do that? :fearful:

**Comment by FezVrasta** [comment]
web moves fast. npm seems here to stay. Yarn is simply a tool over npm, so in case it gets discontinued you can simply use npm.

**Comment by JasonTheProgrammer** [comment]
To preempt the possibility, I'm tempted to just go straight to NPM. Reading up on the topic elsewhere, I see I wouldn't be the only one.

**Comment by FezVrasta** [comment]
Yarn is  backed by Facebook and they use it in production, so I think its future is pretty solid.
Additionally, if tomorrow Yarn dies, you can simply start using npm without even noticing that you changed tool, since they are completely compatible with each others.
The only difference is that Yarn is faster and more reliable.

**Comment by JasonTheProgrammer** [comment]
But Bower was "created at Twitter" (though I don't know if they ever *used* it). Facebook using it in production sounds good in principle, but with the scale of their engineering team they could drop it in a big hurry if they decided to "go in a different direction".

**Comment by FezVrasta** [comment]
That's why the "backed by Facebook" is just one of the points in my list 😉

**Comment by JasonTheProgrammer** [comment]
Fair call, thanks for sharing the thoughts, I'll be sure to keep Yarn in mind when I factor Bower out.

**Comment by FezVrasta** [comment]
https://github.com/FezVrasta/popper.js/issues/390
