### ISSUE TITLE
Unexpected position of popper (placement: 'auto').

### ISSUE THREAD

**Issue by imkremen** [FezVrasta/popper.js#231]
If free space above or under reference element is not enough, it is expected that popper will be placed to the right or left of the element, but this does not happen.

Example: https://codepen.io/imkremen/pen/YVGxeB

**Comment by imkremen** [comment]
I tried to set "flip.behavior: 'clockwise'" but it does't help. https://codepen.io/imkremen/pen/VbKMrL

**Comment by FezVrasta** [comment]
So, the problem with the `auto` placement is derived by the fact that `auto` will use `scrollParent` as `boundariesElement` no matter what you define in the `preventOverflow` modifier.

I'm going to make it use the `boundariesElement` of the `flip` modifier to fix the problem.

**Comment by imkremen** [comment]
@FezVrasta Now I have some misunderstanding about having two "boundariesElement" in different modifiers at the same time.

What I need to expect in this case https://codepen.io/imkremen/pen/PmGBwJ ?

**Comment by FezVrasta** [comment]
So, there are two `boundarisElement` because you can decide how each modifier should behave.

You can have the popper to flip when it hits the boundaries of the `viewport` but have it stay between the boundaries of the `scrollParent`, or any possible mix you may think of.

Usually the default values are the ones you'd expect.

In your case, you are defining `placement: 'top'`, there isn't enough space on the top, so it flips on the bottom. If you reduce the viewport height until there's no space in both the dimensions, the `preventOverflow` modifier will move the popper to keep it between the viewport.

**Comment by alfechner** [comment]
@FezVrasta you're example is so helpful, thank you so much 🚀
