### ISSUE TITLE
[Firefox/Chrome] will-change on parent breaks left edge alignment with position bottom

### ISSUE THREAD

**Issue by mikkelwf** [FezVrasta/popper.js#310]
### CodePen demo

https://codepen.io/mikkelwf/pen/owYBXp

### Steps to reproduce the problem

No steps really, error shows in codepen

### What is the expected behavior?

Box 1 and Box 2's attached popper should both align to the left edge.

### What went wrong?

Box 2's popper is centered under the box, not aligned to the left edge.

### Any other comments?

I'm unsure if this is a browser / css issue, of if popper does some wrong calculations. `transform: translate3d(0,0,0)` breaks as well, so i might not be easily fixable.

**Comment by FezVrasta** [comment]
Umh, that's weird. It happens on Chrome and Firefox, but not in Safari.

I'd say it's a browser specific bug, because `will-change` shouldn't affect the way stuff is rendered, it should just perform optimizations to the transformations, also, it doesn't seem related to the usage of `will-change` in Popper.js itself.

Would you mind create a repro without any JS at all (no Popper.js, just HTML and CSS)? If it happens even there, we may want to open a bug report on the Chrome and Firefox issues tracker.

**Comment by FezVrasta** [comment]
So, I investigated a bit, actually `will-change: transform` will create a new stacking context according to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change)

The problem relies in a problem with `preventOverflow` and the way it handles transformed parents.

**Comment by FezVrasta** [comment]
Fix is ready, I'm writing a test to avoid regressions.

I should really move to Flow... meh

**Comment by mikkelwf** [comment]
Nice.. Awesome..!
