### ISSUE TITLE
[Question] Internet explorer 9 support status

### ISSUE THREAD

**Issue by onigoetz** [FezVrasta/popper.js#327]
Hello,
Just a quick question. I work in a company that still has to support IE9, I love your library and want to use it in our components library but it has to be IE9 compatible.

I see that your tests run on IE 10, what is the status of IE9 ? "might work but don't count on it", or "forget it we use features that will never work on IE9" ?

Thanks in advance and thanks for the great work on this library. If it's not right now, we will definitelyuse your library when we finally drop IE 9 support :)

**Comment by FezVrasta** [comment]
Hi, in the past the library worked on IE9 but I then dropped the support because it required a lot of hacks and specific code to make it work properly and the time needed wasn't worth it.

You may try to run the test suite against IE9 and see how many of them fail to get an idea of what's the status is.
