### ISSUE TITLE
React to height/width changes of popper element

### ISSUE THREAD

**Issue by nikkwong** [FezVrasta/popper.js#334]
Hi guys, it would be great if poppers can react to height/width changes.

Let's say I have a popper that's ```right``` of an element and ```offset``` ```50%``` from the top. When the popper grows, it will no longer be vertically aligned. Is there any way to deal with this currently? Thanks.

**Comment by atomiks** [comment]
+1

I'd like an option to automatically update the position of the popper when its size has changed instead of manually calling `update/scheduleUpdate`

**Comment by FezVrasta** [comment]
I did give a talk few weeks ago where I explained how to obtain this with `react-popper` and `react-resize-aware`.

https://www.youtube.com/watch?v=GoQkbxiD4S0

I don't think this is something I want to add to the core of the library because it adds lot of complexity and makes the library rely on DOM manipulations more than I desire.

**Comment by atomiks** [comment]
I can implement this functionality relatively easily with `MutationObserver` in `mountPopper` in tippy anyway... good question 👍

**Comment by FezVrasta** [comment]
Note that MutationObserver can't detect changes related to CSS
