### ISSUE TITLE
Tooltip is shown after delay even if the pointer is no longer over the element.

### ISSUE THREAD

**Issue by aristidesfl** [FezVrasta/popper.js#399]
https://codepen.io/aristidesfl/pen/Jyvoro

### Steps to reproduce the problem

1.  Create Tooltip.js with a delay show delay of 1000ms
2.  Drive your mouse through the target, without letting the mouse stay over the target for more than 1000ms .
3.  Wait until the tooltip appears

### What is the expected behavior?

The tooltip should never be shown.

### What went wrong?

The tooltip is shown after 1000ms, and it doesn't hide automatically.

**Comment by FezVrasta** [comment]
Hi, please provide a codepen example using the provided template.

**Comment by aristidesfl** [comment]
Added a codepen

**Comment by scottbedard** [comment]
I too am experiencing this issue

**Comment by kkempster94** [comment]
I too am experiencing this issue.

**Comment by FezVrasta** [comment]
Please guys I don't give a shit to know that "you too are reproducing the problem".

The issue is here because I know the problem exists. The only way to see it fixed is to send a PR to fix it. So, stop commenting here.

**Comment by kkempster94** [comment]
I don't mean to directly oppose what you've asked. This'll be my last comment on the issue. I figured that it would be helpful to know the full impact of an issue. If I see an issue that one person opened that has no involvement from other users, I'd be likely to assume that number of users impacted by the issue is pretty low. If you don't feel like the impact is relevant, then so be it. Just thought I would share, not that I could reproduce the problem, as it has been proven to be broken, but that this is an issue which also impacts me.

**Comment by FezVrasta** [comment]
In this case adding a 👍 on the first post is more than enough
