### ISSUE TITLE
How to manage z-index issues?

### ISSUE THREAD

**Issue by sontek** [FezVrasta/popper.js#482]
### CodePen demo
https://codepen.io/sontek/pen/OOMmvN

### Steps to reproduce the problem

The popper is below both the content and the absolute positioned footer.  How can I make sure it is above them?

### What is the expected behavior?

The popper to be above the absolute positioned footer.

### What went wrong?

The popper is below it.

**Comment by FezVrasta** [comment]
https://codepen.io/FezVrasta/pen/QOyvVg ?

The thing is, any `z-index` higher than 3 denotes a lack of understanding of how it works.

**Comment by sontek** [comment]
@FezVrasta Sorry, we have z-index higher than 3 because we use a react component that has set their z-index higher than that and we have to pop above it.

Your pen gets it above the content but not the absolute positioned footer, which is my problem.   Shrink your window so the gray box is closer to the popper

**Comment by FezVrasta** [comment]
`isolation: isolate` is your best friend.

z-index is thought to be used in "stack contexts", you just create small stacks with few elements (and then, few layers)

**Comment by sontek** [comment]
@FezVrasta Yeah, but `isolation` isn't supported in any IE (even modern ones), correct?

**Comment by sontek** [comment]
So what would be the best way to handle a thing like what I'm doing here?    In the codepen you posted its just `z-index: 1` and `z-index: 2` but the popper doesn't go above the absolute positioned element that has the lower z-index.

**Comment by FezVrasta** [comment]
You want to have a stacking context for the page layout, and then on top of it you put a other elements (like the popper) that with just a `z-index: 1` will stay above the rest

**Comment by capr** [comment]
So basically popper.js eschews the problem of browsers missing a global z-index (*), which is the main reason for positioning popups in js in the first place. I kept wondering "how does popper keep the popups on top of everything if it doesn't move them to the root element, since there might be implicit z-stacks created along the path?" Now I know: it doesn't.

(*) Let's face it, stacking contexts are just an abstraction leak of the graphics model. Saying "create shallow context stacks" is not helpful as there's plenty of legit use cases that create implicit z-stacks.

**Comment by thephox1982** [comment]
I was surprised to find that Popper opened up as a child of a parent DOM element rather than being appended to the BODY of the page absolutely positioned at the position of the mouse click event, that would have made this entire situation moot, so now I'm going to have to write code to ignore Popper and open my own popup in it's place.

I must have missed the law/rule book on how to code, I mean I been at this for over 20 years now and never came across anything other than best practices and guidelines. I wasn't aware z-index should never be used and doing anything different than the default built in stacking was illegal and must never be done. Where do I turn my self in for breaking these crimes?

Seriously though, jQuery UI uses z-index positioning for various things that would overlap Popper with how Popper works currently, I guess the people who contribute to that project and so many other projects are armatures who should give up coding and go do something else because they are doing it wrong?

The replies from the creator are enough to make me spend the time to work around Popper and do it my self rather than seek potential solutions to make it work and not get buried under other elements.

**Comment by FezVrasta** [comment]
Popper doesn't move elements to be child of the root element because it's not its responsibility. The library can easily position elements inside complex contexts as well as direct child of root. It's up to the consuming code to decide what to do with it.

My suggestion is not to move elements around the document because it introduces a lot of accessibility issues that need to be manually addressed.

**Comment by chmich** [comment]
What might be needed is something like a scope for z-index/stacking context.

Say you have a top-bar, a left-bar and a content-block. They can be siblings and z-index works great. Regularly the top-bar and the left-bar have a higher z-index than the content-block. The problem is always that the popovers nested anywhere within the content block should all overlap.

If it would be possible to scope a stacking context, lets call it root, for example you could give the popovers this scope so that they are siblings with the top-bar, left-bar and content-block, regardless of their position, our problem would be solved.

For me it is hard to understand that, 2023, in the landscape of web development this feature is not available.

**Comment by FezVrasta** [comment]
`<dialog>` should handle this, I think the new `<popup>` element too

**Comment by chmich** [comment]
@FezVrasta I played a little around and found not so much different behaviour on overlapping for dialog/popup. Except: Opening a dialog by `dialogElement.showModal()`. But thats a dialog in the middle of a page, not a positioned popup.

**Comment by chmich** [comment]
Zurb Foundation, on its [tooltip](https://get.foundation/sites/docs/tooltip.html) is really doing what @capr says!

I did a test: If you hover on this tooltip, (for test i set it to click-open), it creates a div on a root place, above all stacking-contextes and this overlaps all.

**Comment by chmich** [comment]
I have found my way.

In my case every second dropdown-panel content is dragged by GET request.
At root level I have a div with an ID like `#dropdown-panels-box`. This is a wrapper for dropdown panels and in a line with the z-indexes on the first level.
And then an opening script (Rails / Stimulus) that, if no corresponding panel exists, just creates an element inside that box.

This works fine and feels clean.
