### ISSUE TITLE
No obvious way to set absolute position to popper with reference object.

### ISSUE THREAD

**Issue by lflserg** [FezVrasta/popper.js#490]
### CodePen demo

https://codepen.io/lflserg/pen/wPdmEN

### Steps to reproduce the problem

1.  Create custom reference object
2.  Attach a popper to it
3.  Scroll

### What is the expected behavior?

There is an obvious way to make the object attached to the absolute position and not to the viewport.

### What went wrong?

Object is attached to the viewport. 
The way to set absolute position is to create a hidden dom element, and attach popper to it.

**Comment by FezVrasta** [comment]
I don't think I understand what the demo should show, may you elaborate a bit please?

**Comment by FezVrasta** [comment]
If you mean that the tooltip will not scroll together with the page, this happens because the reference object doesn't actually have any DOM context, thus Popper.js is not able to understand which scroll events it have to listen to.

You can manually define the scroll handlers like I did in this demo:
https://codepen.io/FezVrasta/pen/vWXQdq

Or make the reference object provide the needed information for Popper.js to know its DOM context, I never tried this approach but I think you should be able to define a `parentNode` getter that returns the expected parent and it should work, but I'm not sure.

**Comment by lflserg** [comment]
@FezVrasta thank you for your prompt response! I considered similar solution, but dont you think this will make a performance drop compared to binding to hidden DOMelement?

**Comment by FezVrasta** [comment]
I don't think it's going to be a performance bottleneck, you are simply defining your event listeners manually instead of letting Popper.js do it for you.

The fact that you don't have a DOM node as reference element has some advantages, such the fact that reading its informations will be faster than if you wanted to read a real DOM node.
