### ISSUE TITLE
TypeError: Failed to execute'getComputedStyle'on'Window': parameter 1 is parameter

### ISSUE THREAD

**Issue by yuchonghua** [FezVrasta/popper.js#665]
### CodePen demo

https://codepen.io/pen?template=wGqJEz

### Steps to reproduce the problem

1.  [electron-nuxt-element.zip](https://github.com/ElemeFE/element/issues/12135#issuecomment-408312075)
2.  [element-ui-issues](https://github.com/ElemeFE/element/issues/12135#issuecomment-411964187)
3.  [Installation](https://github.com/ElemeFE/element/issues/12135#issuecomment-408312075) 
```shell

wget https://github.com/ElemeFE/element/files/2234482/electron-nuxt-element.zip
unzip electron-nuxt-element.zip
cd electron-nuxt-element
npm i
npm run dev

```

### What is the expected behavior?

Can window.getComputedStyle be changed to element.getRootNode().defaultView.getComputedStyle

### What went wrong?

Document element will be wrong when used in different windows

### Any other comments?

Window uses element.getRootNode().defaultView,
I also expect that not all popup layers are inserted into the root body, but there is an optional insertion point.

![bug-demo](https://user-images.githubusercontent.com/11555571/43303621-1f5bbb14-91a3-11e8-9930-cde58b06ff25.gif)

**Comment by yeziZ** [comment]
[ddv-multi-window](https://github.com/ddvjs/ddv-multi-window) is a multi-tab application for sub-windows across windows. It can be used. The current problem seems to be in the sub-window, dom is in the sub-window, the event is in the main window, but in the [element-ui](https://github.com/ElemeFE/element) in the main window, the sub-window is found. Dom
Preliminary estimates are issues with the isFixed and [getStyleComputedProperty](https://github.com/FezVrasta/popper.js/blob/d01f8683907e103ca7940f93823a8e6512041e1e/packages/popper/src/utils/getStyleComputedProperty.js#L8) methods

**Comment by HadiChen** [comment]
I mainly use [element-ui](https://github.com/ElemeFE/element) in [electron](https://electronjs.org/), but [element-ui-issues-12135](https://github.com/ElemeFE/element/issues/12135#issuecomment-411964187) decided to use [popper.js](https://github.com/FezVrasta/popper.js/blob/1ddf685b14489a63e389c0b52aaa9fc7484b9316/packages/popper/src/utils/getOuterSizes.js#L8-L17). Currently my application is based on [nuxt](https://github.com/nuxt/nuxt.js). This problem is estimated by the [isFixed](https://github.com/FezVrasta/popper.js/blob/08c5d6010346bf9df06e9f81a54fa6c2c51e3639/packages/popper/src/utils/isFixed.js#L12) and [getStyleComputedProperty](https://github.com/FezVrasta/popper.js/blob/1ddf685b14489a63e389c0b52aaa9fc7484b9316/packages/popper/src/utils/getStyleComputedProperty.js#L8) and [getComputedStyle](https://github.com/ElemeFE/element/blob/dev/src/utils/popper.js#L1029) methods of @yeziZ. The problem is that you need to support various pull-down or floating windows without relative roots. You can support the input of an inserted node. In addition, the [window.getComputedStyle](https://github.com/FezVrasta/popper.js/blob/1ddf685b14489a63e389c0b52aaa9fc7484b9316/packages/popper/src/utils/getStyleComputedProperty.js#L13) method needs to be changed to [element.getRootNode().defaultView.getComputedStyle](https://github.com/FezVrasta/popper.js/blob/5e84ac0240bc9551143a8d6647b39eaf02d212a8/packages/popper/src/utils/getWindow.js#L8). The actual application scenario is @yuchonghua. In [electron-nuxt-element](https://github.com/ElemeFE/element/issues/12135#issuecomment-408312075).

**Comment by FezVrasta** [comment]
Feel free to send a PR with a fix please.

**Comment by yuchonghua** [comment]
I will study how to fix it, give me some time, thank you for your support.

**Comment by yuchonghua** [comment]
Is pr a master branch operation or a next branch operation?
/ping @FezVrasta

**Comment by FezVrasta** [comment]
Please work on master, next is a different project
