### ISSUE TITLE
Documentation: Clarify which URLs to use for <script> loading

### ISSUE THREAD

**Issue by mcandre** [FezVrasta/popper.js#819]
Hi, I am working over some stumbling blocks with integrating popper into my application. For example, I wasn't sure which of the many URLs listed on CDNJS to use in my `<script>` tags:

https://cdnjs.com/libraries/popper.js

Could the popper documentation include a mention of which of these to use? I think it's

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/umd/popper-utils.js"></script>
```

But I'm not entirely sure.

**Comment by FezVrasta** [comment]
Hey, CloudFlare is not even an officially supported CDN.

If you click on the Unpkg URL you are directed to the correct URL/file already.

Also, please, read the [dist targets](https://github.com/FezVrasta/popper.js#dist-targets) chapter, since it answers your exact question.

To be honest, I doubt any amount of documentation could help if I then get questions with people trying to use a CDN not even listed in the documentation...
