### ISSUE TITLE
A few policy questions

### ISSUE THREAD

**Issue by wimleers** [FezVrasta/popper.js#823]
Hi there! And thanks for all your excellent work, this library has been super helpful :)

The Drupal project is considering adding this library as one of our dependencies and so we're performing a standard stability review. We're looking into adopting this in https://www.drupal.org/project/drupal/issues/3074267.

I'm curious if you have any official policies documented somewhere WRT to:

- Security releases
  - For example, does more than one version receive security fixes, or only the current version? This is currently not yet an issue since there only is one major version, but I did see that version 2 (branch `next`) is being worked on. So while this may not be a concern yet, it will become one in the future.
- Release windows/cadence
  - For example, do they happen as necessary on any given day, or on a set schedule after a certain passage of time (e.g. once a month)?
- Backwards compatibility guarantees
  - I see the project uses semver, so I assume the major version promises not to break BC. https://github.com/FezVrasta/popper.js/issues?utf8=%E2%9C%93&q=label%3A%22%23+BREAKING+CHANGE%22+ confirms you're being very careful with breaking changes. However, is there any guarantee that a version will be supported for some period of time (an LTS version, for example)?

**Comment by FezVrasta** [comment]
Hi! Thanks for the kind words. Let me try to address your points.

1. Security releases: I can't think of any attacking surface to be honest, but in case a security vulnerability is found I plan to support at least the current version and the previous major one. (v0 + v1, v1 + v2 etc)
2. This is a side project, so I can't provide any guarantees on the amount of hours I can dedicate to it. I may work full time for a week, and then do not even answer to new issues for a month if I'm too busy with my main job and life. I release when there are enough changes or when a lot of people depend on some fix/feature introduced
3. The plan is to strictly follow semver, unfortunately sometimes something that was a bug and gets fixed can break some expectations, so, as with any other JavaScript library, be careful with the upgrades. Just know I use this library at work, and it's used by some big projects (e.g. Bootstrap) so if something breaks it usually gets reported and fixed quickly

**Comment by wimleers** [comment]
1. 👍(I agree that there is a super super low probability of security issues in this JS library!)
2. The release window/cadence question isn't about how fast you're responding. Sorry for not having been more clear! I should've asked it like this: are you willing to coordinate with the Drupal Security Team (https://security.drupal.org/team-members, https://www.drupal.org/drupal-security-team/security-team-procedures) to ensure that security releases happen on the same day? Bugfix release cadence doesn't matter much, but security release windows do matter a lot — see https://www.drupal.org/core/release-cycle-overview#windows.
3. 👍

Thanks so much!

**Comment by FezVrasta** [comment]
About 2, in all honesty, I cant guarantee I'll always be available to cut a release when required by the Drupal Security Team.

I'm not sure I completely understand the implications, but whenever a security issue is discovered I'm going to fix and release the fix as soon as possible.

**Comment by wimleers** [comment]
> I'm going to fix and release the fix as soon as possible.
This is the thing that we're asking about: _releasing the fix as soon as possible_ would be problematic for us. We'd need that release to be coordinated with the Drupal Security Team. That's important to avoid that Drupal will potentially be shipping an insecure release for a long time.

Do you think you could do that? I'm happy to facilitate.

I know the probability of `popper.js` ever having a security release is very slim — but we don't want to deal with more surprises than necessary when solving security problems of course :)

**Comment by FezVrasta** [comment]
I'm not sure I understand... Would you rather have a library wait to ship a security fix (given it is already undisclosed) and have it release it only when you are also able to update, rather than have the library ship the security patch, and maybe have Drupal release a few versions with an outdated version?

**Comment by xjm** [comment]
Thanks @FezVrasta for the quick replies!

Drupal practices [coordinated disclosure](https://en.wikipedia.org/wiki/Responsible_disclosure), which means that (whenever possible) details of the security issue are not disclosed until a fix is ready for release, and maintainers of the affected project collaborate privately to schedule when the vulnerability will be disclosed and fixed. The goal of coordinated disclosure is to make it more likely for users of the library to have a chance to update before potential attackers start exploiting the vulnerability in the old, unpatched version of the software.

So, for example: Drupal core also depends on the CKEditor library. Last year, a security issue in CKEditor was reported to the Drupal Security Team, and we in turn reported it to the CKEditor maintainers. In order to make sure that all CKEditor users could apply this security update at the same time (without giving potential attackers advanced information), CKEditor worked with Drupal to schedule the disclosure and security release for the fix on a day that worked for both projects. Drupal privately tested CKEditor's fix before the release date to ensure it worked with Drupal. Then, [CKEditor released 4.9.2](https://ckeditor.com/blog/CKEditor-4.9.2-with-a-security-patch-released/) on the same day that [Drupal released SA-CORE-2018-003](https://www.drupal.org/sa-core-2018-003). That way, users of both projects had a chance to update safely at the same time. If CKEditor had simply released the patch as soon as it was working for them, without coordinating with Drupal, then Drupal users would have been at higher risk of being exploited because an update was not ready for them.

Similarly, whenever Symfony does a security release, they give us a heads-up about it and a chance to test it privately before the security release goes out, and we release our security updates on the same day. We try to coordinate with our dependencies like that wherever possible. :)

The two things we're most interested in for coordinated disclosure are:
1. Will security issues be kept private until a fix is ready for release?
2. If you have a security advisory that's forthcoming, can you let the Drupal Security Team know and possibly work with us on scheduling a release date? (Our core security release windows are the third Wednesday of the month.)

Thanks again for your feedback!

**Comment by FezVrasta** [comment]
Hey. Yeah that makes sense. I'm okay with it

**Comment by FezVrasta** [comment]
I'm gonna close this since it looks like no more questions are coming.
