### ISSUE TITLE
Enhance inline reference element support

### ISSUE THREAD

**Issue by Justineo** [FezVrasta/popper.js#9]
It will be nice if popper has [Tooltipster](https://github.com/iamceege/tooltipster)-like inline element support. See [here](https://jsfiddle.net/Justineo/v8s7z5xb/embedded/result/).

**Comment by FezVrasta** [comment]
This is pretty nice!

**Comment by FezVrasta** [comment]
Related: https://github.com/FezVrasta/popper.js/issues/193#issuecomment-292014315

**Comment by FezVrasta** [comment]
This could be achieved with a custom modifier that takes the width of the text block on the 4 edges and then centers the popper accordingly... (I think).

**Comment by FezVrasta** [comment]
Closing, feel free to implement it as a custom modifier if you need it.

**Comment by Narretz** [comment]
Hi @FezVrasta could you give me a hint on how this modifier would work? Which modifier would it replace in calculating the position? And could it be implemented so that it works together with the built-in modifiers like shift, preventOverflow etc?

Personally, I think this is a very useful feature, but I assume the complexity would add quite a bit to the core. I think it makes sense as a custom modifier, but I think some more input from you could definitely speed up the process in creating this.

**Comment by josephrocca** [comment]
Current behaviour is definitely counter-intuitive: https://jsbin.com/kulefoduvo/2/edit?html,output That tooltipster approach looks neat!

**Comment by atomiks** [comment]
Here's my current solution for this, using `.getClientRects()`. It requires a sufficient line-height, I think?

https://codepen.io/atomiks/pen/GeBoyW?editors=0010

How would you guys do it?

**Comment by atomiks** [comment]
^ So that behavior is a bit different to the tooltipster one. But it's also useful in cases of interactivity, by making it appear at the rect where the cursor landed.

For the tooltipster case, here's what I came up with: based on the current placement, it will choose the correct rect(s) and "sums" the rects on a particular side.

https://codepen.io/atomiks/pen/jjqbjy

I think the summing behavior also needs to be applied to the CodePen in the above comment as well, since the tooltip can overlap a line when it's not split as in the demo.
